[workspace]
members = ["domain", "usecase"]
# Only check / build main crates by default (check all with `--workspace`)
default-members = ["domain"]
# Example has been deleted, but README.md remains
exclude = []
resolver = "2"
